nacos:
  discovery:
    server-addr: 127.0.0.1:8848
  config:
    server-addr: 127.0.0.1:8848
spring :
  kafka:
    bootstrap-servers: PLAINTEXT://127.0.0.1:9092
    producer:
      retries: 3
      batch-size: 16384 #16K
      buffer-memory: 33554432 #32M
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

    consumer:
     # key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: mygroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-commit-interval: 15

    listener:
      ack-mode: manual_immediate
      #concurrency: 5
      missing-topics-fatal: false
  application:
    name: waitStarttest
  #  cloud:
#    consul :
#      host : localhost
#      port: 8500
#      discovery:
#        port: 12345
#        instance-id: ${spring.application.name}:12345
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
#        register: true   #将游戏网关做为服务节点，注册到Consul上面。
#        service-name: chat  #注册到Consul上面的服务名称，用于区分此服务是否为游戏网关
#        health-check-critical-timeout: 30s
  main:
    web-application-type: none
server:
  port: 8088
game:
  waitstart:
    serverId: 12
    moduleId : 12
    port: 8088
    name: waitStarttest-12
    clusterName: waitStarttest
    host: 127.0.0.1